version: "3.9"

services:
  # Node Application
  api_gateway:
    image: api_gateway_image
    ports:
      - 3000:3000
    environment:
      PORT: 3000

networks:
  default:
    name: api-gateway_default
