version: "3.9"

services:
  # MongoDB Service
  mongo_db:
    container_name: db_container_contentService
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  # Node Application
  user_service:
    build: .
    ports:
      - 3001:3001
    environment:
      PORT: 3001
      DB_CONNECTION_URI: mongodb://mongo_db:27017/pratilipi-ContentService
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
