version: "3.9"

services:
  # MongoDB Service
  mongo_db:
    container_name: db_container_userService
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  # Node Application
  user_service:
    image: user_service_image
    ports:
      - 3003:3003
    environment:
      PORT: 3003
      DB_CONNECTION_URI: mongodb://mongo_db:27017/pratilipi-UserService
      JWT_SECRET: SECRET
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}

networks:
  default:
    name: api-gateway_default
